name: Build and Deploy to The Documentation Site

on:
  # Runs on pushes to the docs folder targeting the default branch
  push:
    branches: ["master","main"]
    paths:
      - docs/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build documentation site
        uses: bcc-code/bcc-documentation-base@v2
        with:
          title: PDF Service
          description: ${{ github.event.repository.description }}
          branch: master
          authentication: 'portal'
