name: Trigger auto deployment for pdf-service-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/pdf-service-api-AutoDeployTrigger-034191ad-ad96-46a0-be7b-7aea280e210d.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: bccplatform.azurecr.io
          username: ${{ secrets.PDFSERVICEAPI_REGISTRY_USERNAME }}
          password: ${{ secrets.PDFSERVICEAPI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bccplatform.azurecr.io/pdf-service-api:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PDFSERVICEAPI_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n pdf-service-api -g pdf-service-prod --server bccplatform.azurecr.io --username  ${{ secrets.PDFSERVICEAPI_REGISTRY_USERNAME }} --password ${{ secrets.PDFSERVICEAPI_REGISTRY_PASSWORD }}
            az containerapp update -n pdf-service-api -g pdf-service-prod --image bccplatform.azurecr.io/pdf-service-api:${{ github.sha }}
